<?php[cite: 1]
echo "Cliente: ";[cite: 1]
$cliente = trim(fgets(STDIN));[cite: 1]
echo "Produto: ";[cite: 1]
$produto = trim(fgets(STDIN));[cite: 1]
echo "Preço unitário: ";[cite: 1]
$preco = (float) trim(fgets(STDIN));[cite: 1]
echo "Quantidade: ";[cite: 1]
$quantidade = (int) trim(fgets(STDIN));[cite: 1]

if ($cliente === '' || $produto === '' || $preco < 0 || $quantidade <= 0) {[cite: 1]
    echo "Dados inválidos.\n";[cite: 1]
    exit;[cite: 1]
}[cite: 1]

$total = $preco * $quantidade;[cite: 1]
echo "===== RECIBO =====\n";[cite: 1]
echo "Cliente: $cliente\nProduto: $produto\n";[cite: 1]
echo "Quantidade: $quantidade\n";[cite: 1]
echo "Total: R$ " . number_format($total, 2, ',', '.') . "\n";[cite: 1]
